version: '3'

services:
  webapp:
    image: guide/webapp:1.0
    build:
      context: .
    ports:
      - "4200:80"
    networks:
      - guide-network
    depends_on:
      - "webapi"

  webapi:
    image: guide/webapi:1.0
    ports:
      - "5000:80"
    networks:
      - guide-network

networks: 
    guide-network:
        driver: bridge